#!/usr/bin/expect
set USAGE "Usage: mod-use-file file ..."

if { $argc < 1 } {
  puts $USAGE
  exit
}

# launch ocaml
spawn -noecho "dune" "utop"

set FIRST 1
proc expect_sharp {use file} {
  global FIRST
  if { $FIRST == 0 } {
    # utop requires three "# " except for the first send
    expect "# "
    expect "# "
  }
  expect {
    "# " {
      send "$use \"$file\";;\n"
      set FIRST 0
      return 0
    }
    "Error" {
      return 1
    }
  }
}

set USE "#mod_use"
# #mod_use all the files except for the last one
for {set i 0} {$i < $argc} {incr i} {
  if { $i == $argc - 1 } {
    # #use the last file (main file)
    set USE "#use"
  }
  set RESULT [expect_sharp $USE [lindex $argv $i]]
  if { $RESULT } {
    # stop reading remaining files if an error occurs
    break
  }
}

interact
