#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: $0 file"
elif [ "$1" = "-version" ]; then
  echo "4.14.2"
else
  SRCFILE="/tmp/${USER}_stepper_src_`date \"+%Y_%m_%d_%H_%M_%S\"`"
  TMPFILE="/tmp/${USER}_stepper_`date \"+%Y_%m_%d_%H_%M_%S\"`"
  DIR="`dirname $1`"
  if [ "$DIR" = "/tmp" ]; then
    # stepper is already running
    stepper $1
  else
    # stepper is launched for the first time
    cd "$DIR"
    # check whether $1 does not have syntax errors
    if [ ! "`ocamlc -stop-after parsing $1 2>&1`" = "" ]; then
      exit 1
    fi
    # remove comments from $1 and store the result in $SRCFILE.ml
    ocamlc -stop-after parsing -dsource $1 > $SRCFILE.ml 2>&1
    SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
    if [ "`grep \"List.\" $SRCFILE.ml`" = "" ]; then
      touch $TMPFILE.ml
    elif [ "`grep \"module List =\" $SRCFILE.ml`" = "" ]; then
      cp $SCRIPT_DIR/list.ml $TMPFILE.ml
    else
      touch $TMPFILE.ml
    fi
    ROOT_DIR="`$SCRIPT_DIR/show-root $DIR`"
    if [ -d "$ROOT_DIR/metro" ]; then
      # For Ochadai use only #####
      # "metro" directory exists.  Expand module definitions
      # Include module definitions
      $SCRIPT_DIR/open-module "metro" $SRCFILE.ml > $TMPFILE-1.ml
      $SCRIPT_DIR/open-module "kansai" $TMPFILE-1.ml > $TMPFILE-2.ml
      $SCRIPT_DIR/open-module "higashi" $TMPFILE-2.ml > $TMPFILE-3.ml
      $SCRIPT_DIR/open-module "global" $TMPFILE-3.ml > $TMPFILE-4.ml
      $SCRIPT_DIR/open-module "seoul" $TMPFILE-4.ml > $TMPFILE-5.ml
      $SCRIPT_DIR/open-module "tree" $TMPFILE-5.ml > $TMPFILE-6.ml
      $SCRIPT_DIR/open-module "redBlack" $TMPFILE-6.ml > $TMPFILE-7.ml
      $SCRIPT_DIR/open-module "heap" $TMPFILE-7.ml >> $TMPFILE.ml
      # For Ochadai use only up to here #####
    else
      # No "metro" directory; do nothing (except for inclusion of List module)
      cat $SRCFILE.ml >> $TMPFILE.ml
    fi
    stepper $TMPFILE.ml
    rm -f $TMPFILE.ml $TMPFILE.cmi $SRCFILE.ml $TMPFILE-{1,2,3,4,5,6,7}.ml
  fi
fi
