#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: $0 file"
elif [ "$1" = "-version" ]; then
  echo "4.14.2"
else
  TMPFILE="/tmp/$USER-stepper-`date \"+%Y-%m-%d-%H:%M:%S\"`"
  DIR="`dirname $1`"
  if [ "$DIR" = "/tmp" ]; then
    # stepper is already running
    stepper $1
  else
    # stepper is launched for the first time
    cd "$DIR"
    if [ "`grep \"List.\" $1`" = "" ]; then
      touch $TMPFILE.ml
    elif [ "`grep \"module List =\" $1`" = "" ]; then
      SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
      cp $SCRIPT_DIR/list.ml $TMPFILE.ml
    else
      touch $TMPFILE.ml
    fi
    if [ -d "metro" ]; then
      # "metro" directory exists.  Expand open Metro etc. (for Ochadai use only)
      cat $1 | sed -e 's/(\*.*\*)//g' | sed -E "/open +Metro[[:>:]]/{
          r metro/metro.ml
          d
      }
      /open +Kansai[[:>:]]/{
          r kansai/kansai.ml
          d
      }
      /open +Higashi[[:>:]]/{
          r higashi/higashi.ml
          d
      }
      /open +Global[[:>:]]/{
          r global/global.ml
          d
      }
      /open +Seoul[[:>:]]/{
          r seoul/seoul.ml
          d
      }" $1 >> $TMPFILE.ml
    else
      # No "metro" directory; do nothing (except for inclusion of List module)
      cat $1 >> $TMPFILE.ml
    fi
    stepper $TMPFILE.ml
    rm -f $TMPFILE.ml $TMPFILE.cmi
  fi
fi
